{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Пробуем залогиниться, используя некорректные данные, ожидаем получить ошибку 400 и текст 'Недостаточно данных для входа'", "steps": [{"name": "Запрос на авторизацию с комбинацией заполненности логина и пароля", "status": "passed", "start": 1743104317806, "stop": 1743104317936}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1743104317936, "stop": 1743104317936}], "parameters": [{"name": "login", "value": "None"}, {"name": "password", "value": "'None'"}], "start": 1743104317806, "stop": 1743104317937, "uuid": "f0d8c028-90a0-4e47-80a6-e468ea402734", "historyId": "f706f914e0367b211883c73aa5498e4d", "testCaseId": "1f5eebca50807e48f6bb7111bf369191", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_empty_fields_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-L3FF6PO"}, {"name": "thread", "value": "20604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}